name: "uptrace-template-basic"

services:
  uptrace:
    image: 'uptrace/uptrace:2.1.0-beta'
    restart: unless-stopped
    volumes:
      - ./uptrace.yml:/etc/uptrace/config.yml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:${UPTRACE_HTTP:?}/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      DEBUG: 2
      UPTRACE_SECRET: ${UPTRACE_SECRET:?}
      UPTRACE_HTTP: ${UPTRACE_HTTP:?}
      UPTRACE_GRPC: ${UPTRACE_GRPC:?}
      UPTRACE_ADMIN_PASSWORD: ${UPTRACE_ADMIN_PASSWORD:?}
      UPTRACE_ADMIN_EMAIL: ${UPTRACE_ADMIN_EMAIL:?}
      UPTRACE_SYSTEM_PROJECT_TOKEN: ${UPTRACE_SYSTEM_PROJECT_TOKEN:?}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:?}
      POSTGRESQL_USER: ${POSTGRESQL_USER:?}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:?}
      REDIS_USERNAME: ${REDIS_USERNAME:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
    ports:
      - '${UPTRACE_GRPC:?}:${UPTRACE_GRPC:?}'
      - '${UPTRACE_HTTP:?}:${UPTRACE_HTTP:?}'
    depends_on:
      - clickhouse
      - postgresql
      - redis

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.123.0
    restart: unless-stopped
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      OTLP_COLLECTOR_GRPC: ${OTLP_COLLECTOR_GRPC:?}
      OTLP_COLLECTOR_HTTP: ${OTLP_COLLECTOR_HTTP:?}
      POSTGRESQL_USER: ${POSTGRESQL_USER:?}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      UPTRACE_HTTP: ${UPTRACE_HTTP:?}
      UPTRACE_GRPC: ${UPTRACE_GRPC:?}
      UPTRACE_SYSTEM_PROJECT_TOKEN: ${UPTRACE_SYSTEM_PROJECT_TOKEN:?}
    ports:
      - '${OTLP_COLLECTOR_GRPC:?}:${OTLP_COLLECTOR_GRPC:?}'
      - '${OTLP_COLLECTOR_HTTP:?}:${OTLP_COLLECTOR_HTTP:?}'
    depends_on:
      uptrace:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:25.8.15.35
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?}
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE:?}
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  postgresql:
    image: postgres:17.9-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRESQL_USER:?}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:?}
      POSTGRES_DB: ${POSTGRESQL_DATABASE:?}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRESQL_USER:?} -d ${POSTGRESQL_DATABASE:?}']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data/pgdata'


  redis:
    image: redis:8.6.1-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 30



volumes:
  clickhouse_data:
  prometheus_data:
  postgresql_data: